name: test

on:
  push:

jobs:
  check:
    name: Svelte Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run check
